### ISSUE TITLE
How we can integrate kubeflow with R

### ISSUE THREAD

**Issue by PriyatamNayak** [SecurityInsanity/dev-loop#41]
Hey we have already integrated Kubeflow with Python
But how we can integrate with R lang

Any steps ?

**Comment by Mythra** [comment]
Hello @PriyatamNayak ,

I'm sorry, but I think you have the wrong place. This repository has nothing to do with the R language, Kubeflow, or Python. This is a local CLI Tool that makes running tasks easier (analgous to a makefile in some ways).

**Comment by Mythra** [comment]
I'm going to go ahead and close this since I'm confident it's mistaken, but if I'm mistaken feel free to comment again :smile:
